name: new_recofarm_app
description: "A new Flutter project."
## Description:  New recofarm application flutter package setting 
## Date : 2024.04.17
## Update
#   2024.04.17 by pdg
  #     - GPS 허용 을 위한 GPS package 추가 
#   2024.04.20 by pdg
  #  yaml  주석  정리 


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

## Flutter SDK 
dependencies:
  flutter:
    sdk: flutter

  ## Libraries 
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  shared_preferences: ^2.2.3


  ##Webview
  webview_flutter: ^4.7.0


  # Card
  card_swiper: ^3.0.1

  ## GET-PATH-HTTP  
  get: ^4.6.6
  path: ^1.9.0
  http: ^1.2.1

  ## FIREBASE
  firebase_core: ^2.28.0
  cloud_firestore: ^4.16.0
  firebase_analytics: ^10.10.0
  firebase_database: ^10.5.0
  firebase_storage: ^11.7.0
  firebase_auth: ^4.19.2
  fluttertoast: ^8.2.5

  ## SQLite
  sqflite: ^2.3.3

  ##GPS
  geocoding: ^2.0.0
  geolocator: ^11.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  xml: ^6.5.0

  ## Chart
  syncfusion_flutter_charts: ^25.1.40
  
  ## Global language setting 
  flutter_localizations:
    sdk: flutter
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    # - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  ## App font setting by pdg
  fonts:

    - family: parisienne
      fonts:
        - asset: assets/fonts/Parisienne-Regular.ttf
    
    - family: Dongle
      fonts:
        - asset: assets/fonts/Dongle-Bold.ttf
        - asset: assets/fonts/Dongle-Light.ttf
        - asset: assets/fonts/Dongle-Regular.ttf
          weight : 700
    - family: Sunflower
      fonts:
        - asset: assets/fonts/Sunflower-Bold.ttf
        - asset: assets/fonts/Sunflower-Light.ttf
        - asset: assets/fonts/Sunflower-Medium.ttf
          weight : 700

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
